apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-lan-only
  namespace: galassmyname-dev
spec:
  # S'applique au Pod MySQL
  podSelector:
    matchLabels:
      app: mysql

  policyTypes:
    - Ingress

  ingress:
    # Bloquer TOUT — aucune règle d'autorisation
    # Résultat : zéro connexion entrante autorisée vers MySQL
    []